export const NavLinks = [
    {
        id:1,
        url:'#',
        Label:'Home'
    },
        {
        id:2,
        url:'#',
        Label:'Company'
    },
        {
        id:3,
        url:'#',
        Label:'Services'
    },
        {
        id:4,
        url:'#',
        Label:'Portfolio'
    },
        {
        id:5,
        url:'#',
        Label:'Blog'
    },
        {
        id:6,
        url:'#',
        Label:'Contact'
    },
]